name: iscat
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.0
  - pip
  - pip:
    - opencv-python
    - pgmpy
    - tqdm
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - tk
